name: build
on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: boost
        run: sudo apt update && sudo apt install -yq libboost-all-dev
      - name: mkdir
        run: mkdir build
      - name: cmake build
        run: cmake -Bbuild -H.
      - name: cmake make
        run: cmake --build build/ --target all
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /home/runner/work/Blackjack-/Blackjack-/build/Blackjack
          asset_name: blackjack-linux
          tag: ${{ github.ref }}
          overwrite: true
          body: "First release"
